
package utils.SMS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TelBank", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.39.241.150/webservice/telbank.asmx?WSDL")
public class TelBank
    extends Service
{

    private final static URL TELBANK_WSDL_LOCATION;
    private final static WebServiceException TELBANK_EXCEPTION;
    private final static QName TELBANK_QNAME = new QName("http://tempuri.org/", "TelBank");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.39.241.150/webservice/telbank.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TELBANK_WSDL_LOCATION = url;
        TELBANK_EXCEPTION = e;
    }

    public TelBank() {
        super(__getWsdlLocation(), TELBANK_QNAME);
    }

    public TelBank(WebServiceFeature... features) {
        super(__getWsdlLocation(), TELBANK_QNAME, features);
    }

    public TelBank(URL wsdlLocation) {
        super(wsdlLocation, TELBANK_QNAME);
    }

    public TelBank(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TELBANK_QNAME, features);
    }

    public TelBank(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TelBank(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TelBankSoap
     */
    @WebEndpoint(name = "TelBankSoap")
    public TelBankSoap getTelBankSoap() {
        return super.getPort(new QName("http://tempuri.org/", "TelBankSoap"), TelBankSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TelBankSoap
     */
    @WebEndpoint(name = "TelBankSoap")
    public TelBankSoap getTelBankSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "TelBankSoap"), TelBankSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TELBANK_EXCEPTION!= null) {
            throw TELBANK_EXCEPTION;
        }
        return TELBANK_WSDL_LOCATION;
    }

}
