
package utils.SMS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TelBankSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TelBankSoap {


    /**
     * 
     * @param accountID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAccountInfo", action = "http://tempuri.org/GetAccountInfo")
    @WebResult(name = "GetAccountInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountInfo", targetNamespace = "http://tempuri.org/", className = "client.GetAccountInfo")
    @ResponseWrapper(localName = "GetAccountInfoResponse", targetNamespace = "http://tempuri.org/", className = "client.GetAccountInfoResponse")
    public String getAccountInfo(
        @WebParam(name = "AccountID", targetNamespace = "http://tempuri.org/")
        String accountID);

    /**
     * 
     * @param dataRow
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetAccountInfo", action = "http://tempuri.org/SetAccountInfo")
    @WebResult(name = "SetAccountInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetAccountInfo", targetNamespace = "http://tempuri.org/", className = "client.SetAccountInfo")
    @ResponseWrapper(localName = "SetAccountInfoResponse", targetNamespace = "http://tempuri.org/", className = "client.SetAccountInfoResponse")
    public String setAccountInfo(
        @WebParam(name = "DataRow", targetNamespace = "http://tempuri.org/")
        String dataRow);

}
